### ISSUE TITLE
Cannot use module installed from npm

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/pvutils#2]
Installed `pvutils` v1.0.9 uses entry point like `main: "./build/utils.js"`. But `build` directory doesn't exist.
This is impossible to use `pvutils` in node projects.
![image](https://user-images.githubusercontent.com/7333669/36261155-7e9464fe-1274-11e8-92a8-f2fa630f08fc.png)

**Comment by YuryStrozhevsky** [comment]
@microshine Fixed.

**Comment by microshine** [comment]
It works. Thank you
